### ISSUE TITLE
emuiibo missing files

### ISSUE THREAD

**Issue by Aes-Sidhe** [Team-Neptune/DeepSea#103]
You didn't include overlay files for other languages found in emuiibo/overlay/lang. Without it emuiibo overlay in tesla doesn't work on non-English system.

**Comment by Slluxx** [comment]
Noticed, fixed in next release. [#7f2](https://github.com/Team-Neptune/DeepSea/commit/7f258a16d8116e031cdddc1c1bfd49bb95351d4d)
