### ISSUE TITLE
Is deepsea-minimal needed?

### ISSUE THREAD

**Issue by steve51184** [Team-Neptune/DeepSea#11]
I'm confused at the need of the minimum package.. isn't this just atmosphere+Hekate with a custom bootlogo and no patches? If it has patches I 100% get it but it's not exactly clear what it's for is all.. all the best :)

**Comment by Slluxx** [comment]
Some people want Atmosphere with hekate but nothing else. Atmosphere itself is created to not be used by or with hekate. Its a thing Kosmos did and we never gave it a second thought.

The statistics say its beeing used/downloaded so we will just continue to deliver it.

**Comment by steve51184** [comment]
Ah didn't know that excellent thanks for the reply 👍🏻
