### ISSUE TITLE
Can't load game

### ISSUE THREAD

**Issue by devilfrenky** [Team-Neptune/DeepSea#111]
I upgrade my CFW from 1.3.1.0 to 1.5.0.0 and DeepSea from 3.3.2 to 4.3.0 and now i can't load any games.
I have already tried to reinstall the games but nothing has changed.
 My ofw is 1.5.1.0, can this be a problem?

**Comment by Slluxx** [comment]
Please join our discord and ask for help there. Github issues are reserved for build related things.
