### ISSUE TITLE
hax4dazy has a problem with their life

### ISSUE THREAD

**Issue by jebediah2** [Team-Neptune/DeepSea#113]
but it's okay we don't judge

**Comment by Slluxx** [comment]
No, you have a problem with leaving it alone.

We did not make our pack any more piracy friendly than atmosphere itself does it. The "fix" linked also does not apply to deepsea specifically. There is nothing special, nothing that allows you to use patches more than atmosphere does and nothing that denies you using sigpatches any more than stock atmosphere does. We do not allow, nor want piracy, especially on Github for very obvious reasons. And for openening this issue, you have earned yourself a lifetime exclusion ticket.
