### ISSUE TITLE
Suggestion: Replace the Old EdiZon App

### ISSUE THREAD

**Issue by sebas05000** [Team-Neptune/DeepSea#115]
My rationale is mostly to have the improved fork of the EdiZon app over the older one since it has a lot of improvements while is still being updated.

https://github.com/tomvita/EdiZon-SE

**Comment by 0DayLin** [comment]
https://github.com/0DayLin/DeepSea-Ultimate/releases

**Comment by Slluxx** [comment]
Replaced in newest release
