### ISSUE TITLE
hekate v6.0.2

### ISSUE THREAD

**Issue by CmpHDL** [Team-Neptune/DeepSea#116]
Add hekate v6.0.2 for HOS 16.0.0 Support.
Attempted to do it myself, got a yellow screen of death.

**Comment by hax4dazy** [comment]
We are waiting for atmosphere to get out of pre-release. Until then we will not update DeepSea.

**Comment by CmpHDL** [comment]
That makes sense, @hax4dazy is there a way I can upgrade it myself and still use deepsea until atmosphere gets out of pre-release status.

**Comment by hax4dazy** [comment]
We will not give anyone support for upgrading their system to the pre-release version of atmosphere. Many of the sysmodules in DeepSea are still broken. Wait for a new release to happen

**Comment by CmpHDL** [comment]
@hax4dazy https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.5.1

**Comment by hax4dazy** [comment]
I know, there's no need to comment about it

**Comment by CmpHDL** [comment]
@hax4dazy Stay humble and continue to crank out that code for free buddy. 👍
