### ISSUE TITLE
README.md File

### ISSUE THREAD

**Issue by ThatFinnDev** [Team-Neptune/DeepSea#119]
Since emuiibo is removed, the "Emulate Amiibo" entry in the features category should be removed too and as far as I know "WLAN" is Deutsch (German) and "WIFI" is english.

**Comment by hax4dazy** [comment]
Emuiibo isn't permanently removed. We're just waiting for the developer to update their homebrew so we can include it back into our pack. Also I'm blaming Slluxx for that spelling mistake lmao, I'll fix it in dev and it'll get pushed to the main branch whenever we do an update.

**Comment by Slluxx** [comment]
sry

**Comment by hax4dazy** [comment]
(finally) fixed in latest release
