### ISSUE TITLE
Suggestion- Add fusee to /bootlader/payloads/

### ISSUE THREAD

**Issue by Arusene-Arsene** [Team-Neptune/DeepSea#122]
this would be really helpful in my opinion. there are tons of people using Hekate to load Fusee, and its not already in the /payloads folder.

**Comment by Slluxx** [comment]
There is absolutely no reason to use the fusee payload though. Especially chainloading hekate > fusee makes no sense in my opinion. If you can provide some benefits though, i am open to have a discussion.

**Comment by Arusene-Arsene** [comment]
ok, so Hekate is a nice toolbox to use in general. second, if i but the wrong fusee payload, ill have to turn it off, enter RCM, and do it again. however, booting the wrong hekate payload still sends you to the normal updated hekate menu. however, this is your choice, and if you decide to add it or not is not in my control. do as you like.

**Comment by hax4dazy** [comment]
We're most likely not going to do it. Feel free to add it on your own but keep in mind that no support will be given to you if you boot this way.
