### ISSUE TITLE
SDSetup is dead (IMPORTANT)

### ISSUE THREAD

**Issue by torsina** [Team-Neptune/DeepSea#134]
as Title says, the maintainer of sdsetup decided it was too much for them currently and just shut things down, ut did put the code on github https://github.com/noahc3/SDSetup/tree/master. The link to sdsetup is the readme has to be removed as well as any reference to the other tools from the same maintainer that also got shut down.

**Comment by hax4dazy** [comment]
Yes, we know. If you read issue number #132 you would have seen that this was already known. We're (still) working on building our own guide.
