### ISSUE TITLE
Booting to black screen after latest update

### ISSUE THREAD

**Issue by Dragonslayersakata** [Team-Neptune/DeepSea#139]
Hello,

I used the All-in-one CFW auto-updater to update Deepsea. After downloading & extracting, I accepted the prompt to reboot to finalize the install. Now it boots to black screen after the Deepsea loading screen.

**Comment by jstaubr** [comment]
I have the same issue

**Comment by Slluxx** [comment]
You should open an issue with the All-in-one repository.
In the meantime, (re-)install deepsea manually. If you need help, please join our discord server. Github issues are reserved for problems with the build script.
