### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by nadrino** [Team-Neptune/DeepSea#14]
Hello there :)

Each time I launch the updater I get this error:

![2020062716585900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/17473586/85925278-9786fc80-b897-11ea-90a0-1ba216a3bc89.jpg)

Any idea from where that could come from ?

**Comment by hax4dazy** [comment]
Did you use Incognito?

**Comment by nadrino** [comment]
Yes I did use IncognitoRCM to remove my prod info, shouldn't I ?

**Comment by hax4dazy** [comment]
Yes you should not use it. It fucked over your SSL sert. Do you have a backup that you can restore to get your prodinfo back?

**Comment by nadrino** [comment]
Yes I have a backup of my prodinfo, but I used Incognito to avoid getting banned on OFW and still get the updates of my games.

Is there a way to run the updater without SSL ?

**Comment by hax4dazy** [comment]
No. You can prevent getting banned by using 90's dns or atmosphere's own "incognito"

**Comment by nadrino** [comment]
Alright, I'll check that out. Is there a reason why you have to use SSL to connect whereas other homebrew don't need it ? If that's not absolutely necessary, you could let us dl update and put a warning message about this issue

**Comment by hax4dazy** [comment]
Github requires SSL.

**Comment by Ninjistix** [comment]
Was also having this issue, other updaters via github work, but this is the only app that gives the SSL error connection.

**Comment by hax4dazy** [comment]
> Was also having this issue, other updaters via github work, but this is the only app that gives the SSL error connection.

You have then used incognito to ""wipe"" your prodinfo. This also wiped your ssl cert. Don't use incognito. If you have a backup restore it and only use 90s dns

**Comment by TechGeekGamer** [comment]
* 90 DNS
