### ISSUE TITLE
Hi there just hint

### ISSUE THREAD

**Issue by KAMELCOLTD** [Team-Neptune/DeepSea#24]
Just want to say if you put edizonSe insted of edizon it will be better since edizon wont get any new update's
but edizonSe always got new update's

**Comment by BOsborneOfficial** [comment]
This should definitely get done -~O

**Comment by BOsborneOfficial** [comment]
> Just want to say if you put edizonSe insted of edizon it will be better since edizon wont get any new update's
> 
> but edizonSe always got new update's
> 
> 
> 
> 

Change the name of the issue to show what the issue actually is not just "here's a hint" that's not helpful on categorizing what the issue is, Bosborne

**Comment by Slluxx** [comment]
As soon as Edizon SE ships the tesla overlay, we will include it
