### ISSUE TITLE
Tesla Overlay doesn't work

### ISSUE THREAD

**Issue by airchase** [Team-Neptune/DeepSea#25]
Tesla is enabled in the DeepSea toolbox, however when holding down **L** + **Down D Pad** + **Down Joystick** nothing happens at all.

**Comment by TechGeekGamer** [comment]
By "Down Joystick", I'm assuming you mean clicking it, right? Correct me if I'm wrong please.

**Comment by airchase** [comment]
Oops, I'm stupid sorry. My only really indicator of how Tesla Overlay was actually launched was in a YouTube video, and he said "down joystick", so my bad.

Not really necessary, but if there a was a quick FAQ / guide quickly highlighting how certain features work, and what apps do what, that might be helpful for people who aren't as involved in the Switch homebrew scene. Case in point, I just found out there's a way to transfer files to the SD card over USB without taking the card out with nxmtp, which is awesome! It wasn't until I Google'd if there was a way to do it and tried to install an app to accomplish it however did I find out I already had one :)
