### ISSUE TITLE
NSAInstaller needs upadte for 11.0.0

### ISSUE THREAD

**Issue by sevenpastzeero** [Team-Neptune/DeepSea#34]
I tried posting this issue in NSAInstaller  repo, but there was no issue tab. The USB installation is not working on 11.0.0.

**Comment by Clydefrosch22** [comment]
yep, also having issues with usb after updating just now.
awoo on latest version works

**Comment by Slluxx** [comment]
We will most likely remove NSA installer and use TinWoo, as it supports nsp, nsz, xci and xcz via the common ways + hard drive support. We made a fork of awoo to remove some of the stuff people may find upsetting. TinWoo solves this and has more features.

**Comment by Clydefrosch22** [comment]
i see, cool.
though i really hope that this endless stream of installers finds an end some day
