### ISSUE TITLE
DeepSea 11.0.1 install nsp needs network to verify whether can start the game.

### ISSUE THREAD

**Issue by troytang** [Team-Neptune/DeepSea#35]
Is there any way to bypass？

**Comment by hax4dazy** [comment]
Did you dump the game yourself?

**Comment by troytang** [comment]
> Did you dump the game yourself?

No. I downloaded nsp games from nxbrew.

I installed all of them on SXOS 11.0.0 and run all right.

so, I dont know which step went wrong.

**Comment by hax4dazy** [comment]
That's piracy and we don't support that

**Comment by troytang** [comment]
> That's piracy and we don't support that

so I should dump nsp myself?

**Comment by hax4dazy** [comment]
Buy the game on the Eshop or get the cart
