### ISSUE TITLE
emuiibo can't access 

### ISSUE THREAD

**Issue by Rowkey** [Team-Neptune/DeepSea#36]
On Release v2.0.2 emuiibo "cant access" message. Didn't have this issue on Release v2.0.1

**Comment by Slluxx** [comment]
This is an issue with Emuiibo and Atmosphere. We hope Emuiibo gets a fix soon and if it does, we will include it in a new release.

**Comment by trsludwig** [comment]
Hi, a new version of emuiibo was released to supporting the latest atmosphere version 0.18.0. 
https://github.com/XorTroll/emuiibo/releases/tag/0.6.2

**Comment by Slluxx** [comment]
DeepSea was updated to 2.0.3 which now includes this version of emuiibo
