### ISSUE TITLE
Can I write via ftp?

### ISSUE THREAD

**Issue by lesca** [Team-Neptune/DeepSea#40]
I am using mac Finder to connect my switch via ftp://ip:5000
Listing and opening files are fine, but when I edit and save a fie (config.ini file), I got error message say no write access. 

Is it possible to enable the write permission for ftpd? I've went through the sys-ftpd/config.ini file, but find no option for this. If it's not supported by now, will it be supported in coming versions? Thanks !

**Comment by Slluxx** [comment]
try to use filezilla. thats a pretty good and afaik the standart ftp tool. If it works with that tool, the issue is mac finder. if it doesnt work, we should take a closer look at ftpd

**Comment by lesca** [comment]
@Slluxx you're right. I need a ftp client to transfer files to my switch! Now I made it work. Thanks.
