### ISSUE TITLE
After upgrade not able to enter into hbl menu

### ISSUE THREAD

**Issue by rkmax** [Team-Neptune/DeepSea#44]
Hi, a couple of days ago I was running previous release of deepsea with firmware 11.0.1 everything was fine but then I left the wireless enabled then the console was updated to 12.0.0 I waited until the firmware 12.0.0 was supported now I upgrade as soon start the console, run hetake go to atmosphere I can see the boot logo of deepsea then the purple logo of atmosphere then a black/white and finally I see the original nintendo logo (not the modified logo from deepsea) any help you cloud provide to be able to run again the homebrew version?

**Comment by hax4dazy** [comment]
Can you please join our [Discord server ](discord.gg/VkaRjYN) so we can better help you with this issue?

**Comment by rkmax** [comment]
Surem thx!
