### ISSUE TITLE
ldn_mitm appears out of date?

### ISSUE THREAD

**Issue by anthr76** [Team-Neptune/DeepSea#47]
Enabling `ldn_mitm` is causing unexpected behavior on my switch. It seems as through for FW 12.0 a new release was published 4 days ago though DeepSea was published 5 days ago. Perhaps it's worth pinning commit shas, or tags so we know if a package is truly out of date?

**Comment by hax4dazy** [comment]
Updated #48

**Comment by anthr76** [comment]
Thanks! Good timing wouldn't it be nice though to pin versions for users to bump or better visibility?
