### ISSUE TITLE
panic occurred

### ISSUE THREAD

**Issue by miguel197843** [Team-Neptune/DeepSea#50]
I couldn't load hekate. it sends a error message. Panic Occurred.... What's the problem?

**Comment by Slluxx** [comment]
Are you using the included payload?

**Comment by miguel197843** [comment]
Yes. hekate_ctcaer_5.5.5.bin

**Comment by Slluxx** [comment]
did you update manually or through aio updater?

**Comment by miguel197843** [comment]
Sorry. Update what? atmosphere?

**Comment by miguel197843** [comment]
I put the files in the sd card, injected hekate payload and then I get the message panic occurred...

**Comment by hax4dazy** [comment]
Can you give use more information then just "panic occurred"? Maybe join our [Discord Server](discord.gg/VkaRjYN) so we can help you better

**Comment by miguel197843** [comment]
![Uploading B376C2CE-EA9C-4B03-9FE0-678743A9C628.jpeg…]()

**Comment by miguel197843** [comment]
Panic occurred while running atmosphere.
Id title: 010041544D530000
Error: std: : abort (0xffe)

**Comment by hax4dazy** [comment]
Does it say that it saved a report?

**Comment by miguel197843** [comment]
> Does it say that it saved a report?

Yes

**Comment by hax4dazy** [comment]
Can you send it to me so I can take a look at it?

**Comment by miguel197843** [comment]
> Can you send it to me so I can take a look at it?

Sure. How can I do that?

**Comment by miguel197843** [comment]
[report_0645d289.bin.zip](https://github.com/Team-Neptune/DeepSea/files/6359493/report_0645d289.bin.zip)

**Comment by miguel197843** [comment]
> Can you set the archive bit in hekate?

Sorry, I didn't understand. I'm not an expert. Did you figure out the problem?

**Comment by hax4dazy** [comment]
Ok so do these steps:

1. Boot into hekate
2. Select tools (at the top)
3. Click on "arch bit * RCM * Touch * Pkg1/2 (at the bottom)
4. Click on fix archive bit
5. wait and see if it fixed anything and then boot your system

**Comment by miguel197843** [comment]
> Ok so do these steps:
> 
> 1. Boot into hekate
> 2. Select tools (at the top)
> 3. Click on "arch bit * RCM * Touch * Pkg1/2 (at the bottom)
> 4. Click on fix archive bit
> 5. wait and see if it fixed anything and then boot your system

It worked! You're genius. Now I have another problem. The games don't work.

**Comment by hax4dazy** [comment]
Did you pirate them?

**Comment by miguel197843** [comment]
> Did you pirate them?

Someone did, not me. Just copied them to the sd card.

**Comment by miguel197843** [comment]
Should I update sigpatches through Aio?

**Comment by hax4dazy** [comment]
We will not provide support for pirated games. You will have to find out yourself how to make them work again.

**Comment by hax4dazy** [comment]
Anyways seeing as this solved your issue I will close this Issue now. Feel free to join our [Discord Server](discord.gg/VkaRjYN) if you have any other questions
