### ISSUE TITLE
the deepsea 2.2.3 didn't work 

### ISSUE THREAD

**Issue by paulzheng91** [Team-Neptune/DeepSea#53]
SciresM released atmosphere0.19.2 a pre build hash of -e8ba6326  on 2021/04/30 ,  The updated zip is  a build hash of "-14ed4e40" released on 2021/05/02,  but Deepsea 2.2.3 still used the previous one.  so it cause black screen when launched cfw-sysnand/emummc,   because of the old  stratosphere component.

**Comment by paulzheng91** [comment]
![reply](https://user-images.githubusercontent.com/83541211/116817365-964dec80-ab98-11eb-94c1-6a97cc4c5766.jpg)

**Comment by paulzheng91** [comment]
![reply](https://user-images.githubusercontent.com/83541211/116817420-d44b1080-ab98-11eb-8b4e-79e3170a9066.jpg)

**Comment by hax4dazy** [comment]
#54 Updated
