### ISSUE TITLE
Can't open HB menù with R trigger pressed

### ISSUE THREAD

**Issue by vipera1212** [Team-Neptune/DeepSea#60]
As the title says when I try to open HB menù with R trigger pressed I get an error that says "Unable to start the software, try again from the home". I'm on official firmware 12.0.1 and DeepSea normal 2.2.5. Any way to fix this? Thank you

**Comment by hax4dazy** [comment]
Do you have sigpatches installed?

**Comment by vipera1212** [comment]
Just updated them with AIO Switch Updater and now It works. Thank you veery much

**Comment by hax4dazy** [comment]
Np!
