### ISSUE TITLE
Crash when start CFW

### ISSUE THREAD

**Issue by huy-nm** [Team-Neptune/DeepSea#61]
I got this error when start Atmosphere CFW
Error Code: 2168-0002 (0x4a8)
Program: 42000....07E51A
Firmware: 12.0.2 (Atmosphere M 0.19.4-master-2ab01ad3)

An error has occurred.

What should I do? Thanks.

**Comment by hax4dazy** [comment]
Hey! This repository's is only for the build script. Please join our [discord server](discord.gg/VkaRjYN) for proper support with any switch related issues.

See you there!
- Team Neptune
