### ISSUE TITLE
tx-chip switch pkg1 wrong 

### ISSUE THREAD

**Issue by fayehoo** [Team-Neptune/DeepSea#69]
I have a chip cracked switch, 10.2  firmware with sxos 3.05 boot.dat.，the emunand system is 10.2 too.
When I use deepsea to enter a emunand system or a nand system, pkg1 errors will appear. I didn't have this problem using m17.1 atmosphere before, If I change 3.05 boot.dat to sx-gear 1.1 boot.dat, it's OK .
Is the guide mode of the atmosphere system or something changed？How to use deepsea with 3.05boot not sx-gear boot.dat???

**Comment by Slluxx** [comment]
If this issue still exists, please ask for help at our discord server.
