### ISSUE TITLE
Support For HOS 13 & Atmosphere 1.1.0

### ISSUE THREAD

**Issue by idarkside** [Team-Neptune/DeepSea#70]
I know it has only just been released but do you plan to add support for HOS 13 and atmosphere 1.1.0 in the near future?

Thanks for the brilliant project

**Comment by Slluxx** [comment]
Atmospheres 13.0.0 support is in pre-release state. We will not update DeepSea as long as its not "officially released".

**Comment by takoyaki99** [comment]
https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.1.1
Official release out, I think,

**Comment by jonahnm** [comment]
> Atmospheres 13.0.0 support is in pre-release state. We will not update DeepSea as long as its not "officially released".

it's officially released now.

**Comment by Slluxx** [comment]
we still have a waiting period on any release. apart from that, we have a reallife too.
be patient.

**Comment by idarkside** [comment]
Sorry guys didn't want to open a can of worms, thanks for the great work, i will close this issue 👍
