### ISSUE TITLE
Downloading new deep sea update

### ISSUE THREAD

**Issue by Jfowler30** [Team-Neptune/DeepSea#72]
Hello I am trying to download the new deep sea update but it keeps coming up with an error code of 2349-008 picture attached as well thanks
![16327161994597612469956189176395](https://user-images.githubusercontent.com/88548756/134844711-e03b1f7a-0839-4c37-9ce6-479739bc2c8d.jpg)

**Comment by Jfowler30** [comment]
Update: managed to get passed error but now I have a black screen and nothing happens, obviously I did something wrong 😅

**Comment by Slluxx** [comment]
well, the title id is for ARMS, which doesnt help a lot.
the error code stands for "LibnxBinderError_NoInit". I assume the homebrew you are using generates it. but im not 100% sure what it stands for.

With the 1.0.0 release of atmosphere, a lot has changed. You should delete every folder from your sdcard except `nintendo` & `emummc` (if you have it) and put the new DeepSea files on it. Please do not just simply override the files.
If you have a patched console or Modchip you might need a few more steps.

**Comment by Jfowler30** [comment]
Oh ok I will do that, I just thought the deep sea updater was supposed to do that no worries

**Comment by Slluxx** [comment]
> Oh ok I will do that, I just thought the deep sea updater was supposed to do that no worries

the deepsea updater is **long** gone. You must be on a version thats over a year old. Switch AiO updater has an updating mechanism for deepsea. thats what you are supposed to use.
