### ISSUE TITLE
Updating Deepsea 3.2 then Updating FW to 13.00

### ISSUE THREAD

**Issue by rjshooter06** [Team-Neptune/DeepSea#73]
I was updating the Deepsea into 3.2, then I update the latest sigpatch that supports HOS 13.00. After that I update FW 13.00 via AIO updater and Daybreak, 

I boot into CFW - sysMMC via hekate, Deepsea boots up, but after got into Home menu, the Switch just hangs there, I cannot do anything, press anything, no errors popped up. I don't know what to do.

But when I tried to boot up into Stock - sysMMC, I can operate my Switch normally, no hangs or anything.

Please help.

**Comment by KBGaming662** [comment]
Mine does this as well.

**Comment by rjshooter06** [comment]
My bad, all I have to do is do a clean install, remove the associated CFW folder, and copy the new one.
