### ISSUE TITLE
v3.3.2 支持 OLED 硬破機嗎？

### ISSUE THREAD

**Issue by leo5579** [Team-Neptune/DeepSea#84]
v3.3.2 支持 OLED 硬破機嗎？

**Comment by Slluxx** [comment]
I have no idea what you want to know. Please use the english language to communicate successfully with us.

I assume you are asking if an oled switch can be modded? Only with a very expensive modchip.
We dont recomend those though.

**Comment by Exorcism0666** [comment]
I used google translate because I am not Chinese but I think he meant "does version 3.2.2 of Deepsea support Nintendo switch OLED?"

**Comment by hax4dazy** [comment]
Honestly, I've got no idea if it does or not. I don't have an oled switch and I don't plan on getting one. If anyone does and they read this feel free to ping me in the [discord server](https://invite.teamneptune.net/)
