### ISSUE TITLE
Tesla or HB Menu not opening

### ISSUE THREAD

**Issue by escobar5** [Team-Neptune/DeepSea#92]
Hi,

I've just installed the latest release of DeepSea, did everything in commonproblemresolver with success, I then launch CFW (SYSNAND) from Hekate and it boots OK, but I cannot open Tesla, nothing happens nor HBMenu.

**Comment by hax4dazy** [comment]
Hey! Could you join our [Discord server](https://invite.teamneptune.net/) for better support? The issues page for this GitHub repo is more meant for issues with the build script.

**Comment by escobar5** [comment]
It seems I was missing sigpatches, because I loaded them, and everything is working fine now.

Thank you
