### ISSUE TITLE
TinWoo installer crashes on v4.2.0 / Atmosphere 1.3.2

### ISSUE THREAD

**Issue by jack2game** [Team-Neptune/DeepSea#98]
As the title suggests. TinWoo version 1.0.5

If run in applet mode, it crashes the entire console with the standard Atmosphere BSOD.

If run in non applet mode, the game itself will be forced to close.

Had to downgrade to v4.1.0 in order to use TinWoo.

**Comment by Slluxx** [comment]
You are right. We need to look into this

**Comment by jack2game** [comment]
This is now fixed with the new TinWoo release.

It is not on their github release page and the hombrew can be updated using its build-in updater, otherwise you'll probably have to compile from their source.

Tested on Firmware 14.1.1 and Atmosphere 1.3.2 with Tinfoil 1.0.11

**Comment by Slluxx** [comment]
I updated tinwoo yesterday from their github and it works.
we just have to compile a new deepsea update
